import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GoogleAdsense from "./components/GoogleAdsense";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleAdsense pId="9101987783305090" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
